"""initial_schema

Revision ID: 20111dee3124
Revises: 
Create Date: 2026-03-12 02:10:24.994332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20111dee3124'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('book_chapter', sa.String(length=100), nullable=True),
    sa.Column('book_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('parent_topic_id', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('student', 'instructor', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('classes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('instructor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('academic_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('lessons',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('topic_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('princeton_section', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('class_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.Enum('active', 'dropped', 'completed', name='enrollment_status'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_id')
    )
    op.create_table('materials',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lesson_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('pdf', 'video', 'link', 'visualization', name='material_type'), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problems',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('topic_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lesson_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('coding', 'multiple_choice', 'open_response', name='problem_type'), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty_level'), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.Column('solution_code', sa.Text(), nullable=True),
    sa.Column('grading_rubric', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('book_reference', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_problems_published', 'problems', ['is_published'], unique=False)
    op.create_index('idx_problems_topic', 'problems', ['topic_id'], unique=False)
    op.create_index('idx_problems_type_difficulty', 'problems', ['type', 'difficulty'], unique=False)
    op.create_table('student_topic_mastery',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('topic_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('class_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('problems_attempted', sa.Integer(), nullable=False),
    sa.Column('problems_passed', sa.Integer(), nullable=False),
    sa.Column('total_hints_used', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'topic_id', 'class_id')
    )
    op.create_index('idx_mastery_student_class', 'student_topic_mastery', ['student_id', 'class_id'], unique=False)
    op.create_index('idx_mastery_topic_score', 'student_topic_mastery', ['topic_id', 'mastery_score'], unique=False)
    op.create_table('ai_tutor_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('problem_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('langfuse_trace_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_gaps',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('class_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('topic_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('problem_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('failure_rate', sa.Float(), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('langfuse_trace_id', sa.String(length=255), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gaps_class', 'knowledge_gaps', ['class_id', 'failure_rate'], unique=False)
    op.create_index('idx_gaps_topic', 'knowledge_gaps', ['topic_id'], unique=False)
    op.create_table('learning_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('class_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('topic_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('lesson_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('problem_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('material_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('event_type', sa.Enum('lesson_opened', 'material_viewed', 'problem_started', 'problem_submitted', 'hint_requested', 'video_played', 'coding_session_started', 'coding_session_ended', 'page_visit', name='event_type'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_class_type', 'learning_events', ['class_id', 'event_type'], unique=False)
    op.create_index('idx_events_student', 'learning_events', ['student_id', 'occurred_at'], unique=False)
    op.create_table('problem_hints',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('problem_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('socratic_question', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'level')
    )
    op.create_table('problem_options',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('problem_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_test_cases',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('problem_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('problem_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('class_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('submitted_code', sa.Text(), nullable=True),
    sa.Column('submitted_answer', sa.Text(), nullable=True),
    sa.Column('selected_option_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('pending', 'passed', 'failed', 'grading', name='submission_status'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['problem_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submissions_class', 'submissions', ['class_id'], unique=False)
    op.create_index('idx_submissions_class_date', 'submissions', ['class_id', 'submitted_at'], unique=False)
    op.create_index('idx_submissions_correctness', 'submissions', ['problem_id', 'is_correct'], unique=False)
    op.create_index('idx_submissions_problem', 'submissions', ['problem_id'], unique=False)
    op.create_index('idx_submissions_student', 'submissions', ['student_id'], unique=False)
    op.create_index('idx_submissions_student_problem', 'submissions', ['student_id', 'problem_id'], unique=False)
    op.create_table('ai_grading_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('submission_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('rubric_score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('langfuse_trace_id', sa.String(length=255), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('hint_requests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('problem_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('submission_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('context_code', sa.Text(), nullable=True),
    sa.Column('hint_delivered', sa.Text(), nullable=False),
    sa.Column('trigger_reason', sa.String(length=255), nullable=True),
    sa.Column('langfuse_trace_id', sa.String(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hint_requests')
    op.drop_table('ai_grading_results')
    op.drop_index('idx_submissions_student_problem', table_name='submissions')
    op.drop_index('idx_submissions_student', table_name='submissions')
    op.drop_index('idx_submissions_problem', table_name='submissions')
    op.drop_index('idx_submissions_correctness', table_name='submissions')
    op.drop_index('idx_submissions_class_date', table_name='submissions')
    op.drop_index('idx_submissions_class', table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('problem_test_cases')
    op.drop_table('problem_options')
    op.drop_table('problem_hints')
    op.drop_index('idx_events_student', table_name='learning_events')
    op.drop_index('idx_events_class_type', table_name='learning_events')
    op.drop_table('learning_events')
    op.drop_index('idx_gaps_topic', table_name='knowledge_gaps')
    op.drop_index('idx_gaps_class', table_name='knowledge_gaps')
    op.drop_table('knowledge_gaps')
    op.drop_table('ai_tutor_sessions')
    op.drop_index('idx_mastery_topic_score', table_name='student_topic_mastery')
    op.drop_index('idx_mastery_student_class', table_name='student_topic_mastery')
    op.drop_table('student_topic_mastery')
    op.drop_index('idx_problems_type_difficulty', table_name='problems')
    op.drop_index('idx_problems_topic', table_name='problems')
    op.drop_index('idx_problems_published', table_name='problems')
    op.drop_table('problems')
    op.drop_table('materials')
    op.drop_table('enrollments')
    op.drop_table('lessons')
    op.drop_table('classes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('topics')
    # ### end Alembic commands ###
